add `TabLink` to support the Design Portal `Playground` Component
avaya-dux/neo-library-react pull request #200
Opened 2022-07-28 15:57 UTC by joe-s-avaya

[Link to updated components in Deploy Preview](UPDATEMEWITHALINK)

Put the most important information here. The content that any reviewer should see and read first (after the PR title).

**EXAMPLE IMAGE(S):**
[PUT EXAMPLES HERE, such as an image of the new tests, or important use case added by this update]

**EXAMPLE FUNCTIONALITY GIF:**
[PUT EXAMPLE GIF HERE]

**IMPORTANT NOTES:**
- Put any secondary, but still important, notes here
- May be bullets or a single sentence/paragraph

2022-07-28 16:48 UTC, joe-s-avaya commented on src/components/Tab/TabComponents.tsx
> +};
I don't like this pattern, but it works, and it has a bunch of tests, so I'm running with it. Feels wrong to built a component just to always return `null` though.

2022-07-28 16:51 UTC, joe-s-avaya commented on src/components/Tab/TabUtils.test.jsx
> +            "content": undefined,
@yangAtSpoken, I'm unsure what change I made to cause this update to a snapshot to happen. Can you advise if this is a problematic change?

2022-07-28 16:53 UTC, joe-s-avaya commented on src/components/Tab/Tabs.stories.tsx
> +          <TabLink href="https://kagi.com/faq">Kagi Search Engine</TabLink>
Note that a `TabLink` _does not_ have an associated `TabPanel` as it is only a link.

2022-07-28 17:43 UTC, yangAtSpoken commented on src/components/Tab/TabComponents.tsx
> +};
Components like this serve the purpose of type checking user input.

2022-07-28 18:22 UTC, yangAtSpoken commented on src/components/Tab/TabUtils.tsx
> +      panels[index] && !!props?.href ? panels[index].props : undefined;
Logic here is problematic. If there is no panel for TabLink, content should be undefined when props.href is defined.  Also since there are more tabs than panels, use a different index to access a panel.

2022-07-28 18:24 UTC, yangAtSpoken commented on src/components/Tab/TabUtils.tsx
> +      panels[index] && !!props?.href ? panels[index].props : undefined;
If tab is a TabLink, do not increment panel index; otherwise, get the panel and increment it.

2022-07-28 18:24 UTC, yangAtSpoken commented on src/components/Tab/TabUtils.test.jsx
> +            "content": undefined,
See comment below.

2022-07-28 18:25 UTC, yangAtSpoken requested changes
left comments.

2022-07-28 18:53 UTC, joe-s-avaya commented on src/components/Tab/TabUtils.tsx
> +      panels[index] && !!props?.href ? panels[index].props : undefined;
I think what you're saying is: "right now the code will break if the `TabLink` is not at the very end, fix that"

Is that correct?

2022-07-28 19:09 UTC, joe-s-avaya commented on src/components/Tab/TabUtils.test.jsx
> +            "content": undefined,
ah, I see, fixed it (not in an ideal way, but I'm working on it)

2022-07-28 20:08 UTC, joe-s-avaya commented on src/components/Tab/TabUtils.tsx
> +      panels[index] && !!props?.href ? panels[index].props : undefined;
@yangAtSpoken I have another test or two to write, but I think that I've resolved the issue you've pointed out. Please let me know if you see any remaining issues.

2022-07-28 21:34 UTC, yangAtSpoken commented on src/components/Tab/TabUtils.tsx
> +      return buildSingleTabPropsHasAssociatedPanel(tab, panels.shift());
Looks good with that shift().

2022-07-28 21:34 UTC, yangAtSpoken approved these changes

2022-07-28 22:02 UTC, joe-s-avaya commented
@yangAtSpoken, I see that you've already approved this, but I've added two unit tests. Can you take a look at them to make sure you agree with the logic?

2022-07-29 14:26 UTC, thota499 approved these changes

2022-07-29 14:26 UTC, merged